export const wedding = {
  groom: {
    name: "Aniruddha",
    fullName: "Aniruddha Mazumder",
    line: "Son of Amalendu Mazumder & late Sampa Mazumder",
    origin: "Kolkata, West Bengal",
    note: "Bringing the warmth, joy, and soulful traditions of Kolkata as we embark on this sacred journey of companionship.",
    image: "/images/groom.png",
    imagePosition: "center 22%",
    imageScale: 1.15,
  },
  bride: {
    name: "Megha",
    fullName: "Megha R",
    line: "Daughter of Rajeevan P & Reeja V",
    origin: "Calicut, Kerala",
    note: "Rooted in love, grace, and rich memories of Calicut, ready to write our new chapter of shared laughter and dreams.",
    image: "/images/bride.png",
    imagePosition: "32% 16%",
    imageScale: 1.45,
  },
  // 6 December 2026, 11:30 AM IST
  dateISO: "2026-12-06T11:30:00+05:30",
  endISO: "2026-12-06T15:00:00+05:30",
  dateLabel: "Sunday, 6 December 2026",
  dateShortLabel: "06 · 12 · 2026",
  dayNumber: "06",
  monthYear: "December 2026",
  timeLabel: "11:30 AM onwards",
  muhurthamLabel: "Muhurtham · 11:30 AM – 12:00 PM",
  venue: {
    name: "Kadody Convention Centre",
    city: "Calicut, Kerala",
    address: "Mavoor, Kozhikode, Kerala 673661",
    mapUrl: "https://maps.app.goo.gl/tz9BhUxMKUeopCPm8?g_st=aw",
  },
};
